#!/bin/bash
session="manino"
daemon="daemon"

#check if session [session] is running
tmux has-session -t $session 2>/dev/null
if [ $? != 0 ]; then
#kill running tmux session
  tmux kill-session -t $session
fi
tmux has-session -t $daemon 2>/dev/null
if [ $? != 0 ]; then
#kill running tmux session
  tmux kill-session -t $daemon
fi

#create new tmux session for [session] and [daemon]
tmux new-session -d -s $daemon  -c /home/bigload/serverfiles
tmux new-session -d -s $session -c /home/bigload/serverfiles
sleep 1
for i in 5 4 3 2 1; do
        printf 'Server starting in %s... (press CTRL-C to cancel)\n' "${i}"
        sleep 1
    done
tmux send-keys -t ${session}:0 ./manino Enter
tmux send-keys -t ${daemon}:0  "./autorestart $session" Enter

# Attach to created session
tmux attach-session -t $session
